### ISSUE TITLE
"user: Current not implemented on darwin/386" when authenticating

### ISSUE THREAD

**Issue by olgagalchenko** [remind101/deploy#19]
Got the latest built version of deploy. Tried to run deploy:
○ → deploy
github.com username: olga@remind101.com
github.com password for olga@remind101.com (never stored): 
user: Current not implemented on darwin/386

@paul-musgrave is getting the same error with v. 0.0.2 even though he has used 'deploy' successfully in the past.

**Comment by ejholmes** [comment]
@paul-musgrave mind trying the amd64 binary?

**Comment by paul-musgrave** [comment]
Sure. Yeah, the 0.0.3 amd64 binary seems to be working for me.

**Comment by ejholmes** [comment]
Cool. Probably no reason to actually post the i386 binary, think all recent macs are amd.
