### ISSUE TITLE
Show a diff between last deployment

### ISSUE THREAD

**Issue by ejholmes** [remind101/deploy#26]
It would be pretty cool if we could show a git diff between the last deployment to an environment. I think we could do this by:
1. Find the last github deployment the the environment.
2. Compare the current ref, with the old sha using [this](https://developer.github.com/v3/repos/commits/#compare-two-commits) api endpoint.
3. Display the diff.

**Comment by mrubens** [comment]
A simple way of doing steps 2 and 3 would be to spit out a URL like https://github.com/remind101/r101-frontend/compare/old_sha...current_sha
